### ISSUE TITLE
[vaultwarden] guide is broken

### ISSUE THREAD

**Issue by schneider-de-com** [Uberspace/lab#1100] opened 2021-08-31 19:41 UTC
The guide for Vaultwarden does not work anymore. After entering the command "cargo build -j 1 --release --features sqlite" build stops with the message that there are modules that are not needed. We added a banner to the guide to signal the broken state.

If you have any insights, please comment on this issue. Pull requests fixing the guide are also highly appreciated. If the guide does not get fixed within two months, we will remove it from the lab, as documented in the [broken guides policy](https://github.com/Uberspace/lab/blob/main/BROKEN_GUIDES.md).

@brutus  @sruf @quadratmuede @pxlfrk FYI.

**Comment by pxlfrk** [comment] 2021-09-03 08:24
Hey @permanentmedia, thanks for your Contribution and hint regarding the error.
I am the original author of the guide and tested the guide in its current state yesterday on a brand new uberspace.

I can confirm the warning you describe, but it's just a compiler warning, **not an error.**
If you let run the build process after the warning shows the build finishes as expected.

```
[user@host vaultwarden]$ cargo build -j 1 --release --features sqlite
   Compiling vaultwarden v1.0.0 (/home/$USER/vaultwarden)
warning: unused imports: `Build`, `Rocket`, `self`
  --> src/util.rs:7:15
   |
7  |     fairing::{self, Fairing, Info, Kind},
   |               ^^^^
...
10 |     Data, Request, Response, Rocket, Build
   |                              ^^^^^^  ^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: 1 warning emitted

    Finished release [optimized] target(s) in 8m 53s
```

So instead of marking the guide as broken i would prefer adding a hint that a warning may occur.
Some words regarding the needed workaaround with the `async`-branch:
Vaultwarden is build upon/with [Rocket](https://github.com/SergioBenitez/Rocket) that in turn needs a rust nightly or dev version to compile successfully (see #708). Rocket has alredy implemented [rust stable](https://github.com/SergioBenitez/Rocket/issues/19), this changes will be released with Rocket 0.5 which is [mostly finished](https://github.com/SergioBenitez/Rocket/milestone/8). As soon as this new Rocket version is released, vaultwarden [will update its dependencies](https://github.com/dani-garcia/vaultwarden/issues/712#issuecomment-658206248) and our patch and hopefully also this warning will be gone.

**Comment by permanentmedia** [comment] 2021-09-03 14:34
Hey @pxlfrk 

thank you for analysing the warning. 

My Uperspace was not a new Uberspace unfortunately, turning off all other services helped complete the build process. 

I think the hint that the build process consumes a lot of RAM and all other processes should be shut down is also helpful.

**Comment by noave** [comment] 2021-12-13 17:56
closing here because the dependency issues of vaultwarden are already handled in https://github.com/Uberspace/lab/issues/708 and the memory issue came up again at https://github.com/Uberspace/lab/issues/1160

**Closed by noave** 2021-12-13 17:56 UTC
