### ISSUE TITLE
[vaultwarden] compiler is killed during install/upgrade

### ISSUE THREAD

**Issue by SalocinHB** [Uberspace/lab#1160] opened 2021-12-13 12:54 UTC
see https://twitter.com/cblte/status/1470153178155044866

**Comment by noave** [comment] 2021-12-13 17:59
this is more or less a duplicate of https://github.com/Uberspace/lab/issues/1100 and in the guide the problem is already mentioned:

> If that doesn’t work the first time and the build failed, just try again until it’s done. Further ignore compiler-warnings regarding unused imports as they sould be gone as soon as the dependencies are updated (see linked Issue above). The build process of vaultwarden can take from 10 to 25 minutes will consume almost the entire system memory. Preferably stop other running services on your uberspace temporarily to prevent running into system memory issues.

however, I think it would be good to rephrase the note there and refer to the actual error message `SIGKILL`.

**Closed** 2022-01-07 12:26 UTC
