### ISSUE TITLE
[pretix] Broken Guide(?)

### ISSUE THREAD

**Issue by Lukas2112** [Uberspace/lab#1144] opened 2021-11-24 23:16 UTC
https://lab.uberspace.de/guide_pretix.html

It seems to me that there are inconsistencies in the instructions that cause it to fail. Does anyone else have this and could confirm my assumption? Of course, I may have overlooked something.

**Comment by SalocinHB** [comment] 2021-12-09 16:43
duplicate of #1054

**Closed by SalocinHB** 2021-12-09 16:43 UTC
