### ISSUE TITLE
[pleroma] guide seems to be broken

### ISSUE THREAD

**Issue by pascoda** [Uberspace/lab#1345] opened 2022-11-08 13:27 UTC
we were informed, and could reproduce, that setting up pleroma currently does not work (neither with new, nor with older versions). 

@taddydevil - can you help?

**Comment by taddydevil** [comment] 2022-11-08 15:57
Do you have _some_ more informations for me? :) 
Error in compiling, dependencies or something else?

**Comment by taddydevil** [comment] 2022-11-09 17:41
**Oo.** 

Please try Erlang 22 @custompyramidfellow . On my working instance with Pleroma 2.4.0 I can compile prometheus_ex.

On my other U7 I can't compile idna, maybe a memory issue. But what I saw in your logs is you have no issues with idna, so this should be not a problem for you.

**Comment by taddydevil** [comment] 2022-11-11 14:51
Nice! 

But how?
I am pretty sure that Pleroma once worked with Erlang version 24 - Uberspace itself has adapted the guide to 24, they do not do that without testing.
However, there must be a reason why I continue to use 22 on my production instance.
I guess 22 is safe until the Uberspace team removes the libraries. Similar to PHP7 - and every damn Pleroma update must be checked for compatibility for that time. 

This issue should remain open until 24 is running again.

Never touch a running version :p

**Comment by taddydevil** [comment] 2022-11-14 10:17
@pascoda I can reproduce that pleroma 2.4.4 / the compiling of prometheus_ex works only with Erlang 22. The guide should be adapted to Erlang 22 and everything is fine - can you do that?

Background:

There is a active issue in prometheus_ex repo already with a fix:
https://github.com/deadtrickster/prometheus.ex/issues/48

> Elixir 1.14 changed Kernel.Utils.defdelegate/2 into Kernel.Utils.defdelegate_each/2

There are two ways to "fix" the compiling.

* Change erlang to 22 temporarily until fix https://github.com/deadtrickster/prometheus.ex/pull/47 is merged and copied to pleroma git
**my recommendation because pleroma developing is slooooow**
* Change mix.exs. Search for `prometheus_ex`, exlude the pleroma source and add the original source with fixed branch `{:prometheus_ex, git: "https://github.com/lanodan/prometheus.ex", branch: "fix/elixir-1.14", override: true},
      {:prometheus_plugs, "~> 1.1"},`
**Tested and works without any issues. But local edited configs from a replicated repo are not cool imho. This will blew up the lab guide.** 
```
      ...
      {:prometheus, "~> 4.6"},
#      {:prometheus_ex,
#       git: "https://git.pleroma.social/pleroma/elixir-libraries/prometheus.ex.git",
#       ref: "a4e9beb3c1c479d14b352fd9d6dd7b1f6d7deee5",
#       override: true},
      {:prometheus_ex, git: "https://github.com/lanodan/prometheus.ex", branch: "fix/elixir-1.14", override: true},
      {:prometheus_plugs, "~> 1.1"},
      ...
```

**Comment by thisven** [comment] 2022-11-14 15:51
I can confirm that both solutions @taddydevil mentions are working, but this is an issue that should be fixed upstream, soon.

**Comment by thisven** [comment] 2022-11-17 11:59
But don't try to switch to Erlang 22 in production as it breaks your installation. I had to learn that the hard way. :unamused:

**Comment by hikerus** [comment] 2022-11-28 10:08
Pleroma 2.4.5 is out. Is there a chance to make an upgrade to this new version or does is it fail as well? I wouldn't use my installation to test this.

**Comment by taddydevil** [comment] 2022-11-28 15:40
Yep, prometheus_ex source changed to the solution I mentioned before.
Line 167 at https://git.pleroma.social/pleroma/pleroma/-/blob/develop/mix.exs

Compiled it "successfully"... but only with `mix deps.compile prometheus_ex`. But there is a new error. I`ll check this out.

**Comment by thisven** [comment] 2022-11-30 09:35
I can confirm that updating to 2.4.5 works without errors using Erlang version 22. Is it safe to just switch to v24 now?

**Comment by taddydevil** [comment] 2022-11-30 15:46
Erlang 24 is totally safe now. Erlang 25 will be experimental (its working with my instance, so just now "it works" too)

@pascoda Btw the guide is not broken anymore with the latest stable release. Can you undo the hint in the guide and close this issue?

**Comment by hikerus** [comment] 2022-11-30 18:59
My upgrade to 2.4.5 failes - with Erlang 24 or Erlang 25

Also a fresh installation of Pleroma fails:
mix: Compilation failed due to warnings while using the --warnings-as-errors option

So my instance is dead now.

**Comment by taddydevil** [comment] 2022-11-30 19:22
Whats your compilation command? At which application does it fail? Can you show us some more of the log (before, after the fail)?

**Comment by hikerus** [comment] 2022-11-30 20:15
I had some merging conflicts in Git - after solving them it compiles the develop version - but there are tons of warning messages. After that the instance is up again.

**Comment by taddydevil** [comment] 2022-11-30 20:19
Had the warning messages too but without any known issues now. If your federation won't work, remove the directorys `_build` & `deps` and run again `mix deps.get` and `MIX_ENV=prod mix ecto.migrate`. Can be related with Erlang 25, or with the different versions you compiled before (your tries with 24 / 25).

Nothing to worry about.

**Comment by taddydevil** [comment] 2022-12-30 13:53
Btw, update Pleroma 2.5.0 working perfectly fine. Follow the update instructions in the lab and be happy with the latest major release.

**Comment by thisven** [comment] 2023-01-03 15:53
Copy that. I just switched to Erlang 25 and upgraded Pleroma to v2.5.0.

Although I noticed three error messages, they don't seem to impair Pleroma from running.
```
==> pleroma
Compiling 592 files (.ex)

[error] Loading of /home/$USER/pleroma/_build/prod/lib/gen_smtp/ebin/mimemail.beam failed: :badfile
[error] The following dependencies are required to use Swoosh.Adapters.Sendmail:
- mimemail from :gen_smtp

[error] beam/beam_load.c(86): Error loading module mimemail:
  lambda already defined for label 491. To fix this, please recompile this module with an OTP 25 compiler.
```

**Closed** 2023-02-14 10:51 UTC
